frontend:
  extends:
    file: config/development.yml
    service: common
  build: ./frontend/
  environment:
    NODE_ENV: development
  ports:
   - "9000:9000"
  volumes:
   - ./frontend/:/app

backend:
  environment:
    NODE_ENV: development
  extends:
    file: config/development.yml
    service: common
  build: ./backend/
  ports:
   - "8000:8000"
  volumes:
   - ./backend/:/app
  links:
   - db

router:
  build: ./router/
  ports:
   - "8500:8500"
  volumes:
   - ./router/:/app

db:
  image: mongo:latest
  ports:
   - "27017:27017"

registry:
  image: registry:2
  ports:
   - "5000:5000"

proxy:
  extends:
    file: config/development.yml
    service: common
  build: ./registry-proxy/
  environment:
    NODE_ENV: development
  ports:
   - "9500:9500"
