frontend:
  build: ./frontend/
  ports: 
   - "9000:9000"
  volumes:
   - ./frontend/:/app

db:
  image: mongo:latest
  ports:
   - "27017:27017"

registry:
  image: registry:latest
  ports:
   - "5000:5000"