frontend:
  build: ./frontend/
  ports: 
   - "9000:9000"
  volumes:
   - ./frontend/:/app

backend:
  build: ./backend/
  ports:
   - "8000:8000"
  volumes:
   - ./backend/:/app

db:
  image: mongo:latest
  ports:
   - "27017:27017"

registry:
  image: registry:latest
  ports:
   - "5000:5000"